{'DateTime': '2024-03-27 14:26:00', 'Question': 'how many records in year 2023 in Job CountByJobOpenDate Table?', 'Answer': "Select count(*) from JobCountByJobOpenDate where JobOpenDate >= '2023-01-01' and JobOpenDate < '2024-01-01'"}
{'DateTime': '2024-03-27 16:40:36', 'Question': 'I need to see yearly No of jobs count. Use JobCountByJobOpenDate table', 'Answer': '```sql\nSELECT\n  SUBSTRING(JobOpenDate, 1, 4) AS Year,\n  COUNT(*) AS JobCount\nFROM JobCountByJobOpenDate\nGROUP BY\n  Year\nORDER BY\n  Year;\n```'}
{'DateTime': '2024-03-27 22:07:00', 'Question': 'I need to see yearly No of jobs count. Use JobCountByJobOpenDate table', 'Answer': 'Select YEAR(`JobOpenDate`) AS `Year`, COUNT(*) AS `No of Jobs`\nFROM `JobCountByJobOpenDate`\nGROUP BY YEAR(`JobOpenDate`)\nORDER BY YEAR(`JobOpenDate`);'}
{'DateTime': '2024-03-27 22:12:51', 'Question': 'how many records in year 2023 in Job CountByJobOpenDate Table?', 'Answer': 'Select count(*) from JobCountByJobOpenDate where CAST(SUBSTRING(JobOpenDate,1,4) AS INT) = 2023'}
{'DateTime': '2024-04-03 09:55:35', 'Question': 'what atop 5 seq freight destination from colombo?', 'Answer': "Select OriginCity , SUM(TEUSum), Count(*) from RevandVolume_ShipmentDate\n                    where ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE() \n                    and DestCity = 'Colombo'\n                    and MainDepCode = 'FES'\n                    Group by OriginCity order by SUM(TEUSum) DESC"}
{'DateTime': '2024-04-03 09:57:49', 'Question': 'How many shipments have we imported from France in last 3 months', 'Answer': "select count(RVM.ShipmentNumber) from RevandVolume_ShipmentDate RVM\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity = 'Freance'"}
{'DateTime': '2024-04-03 10:00:05', 'Question': 'I want to know How many shipments have we imported from Paris in last 3 months?', 'Answer': "```sql\nselect count(RVM.ShipmentNumber) from RevandVolume_ShipmentDate RVM\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity = 'Paris'\n```"}
{'DateTime': '2024-04-03 10:04:26', 'Question': 'I want to know How many shipments have we imported from Chittagong in last 3 months?', 'Answer': "select count(RVM.ShipmentNumber) from RevandVolume_ShipmentDate RVM\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity = 'Chittagong'"}
{'DateTime': '2024-04-03 10:05:46', 'Question': 'I want to know How many shipments have we imported from Dhaka in last 3 months?', 'Answer': "select count(RVM.ShipmentNumber) from RevandVolume_ShipmentDate RVM\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity = 'Dhaka'"}
{'DateTime': '2024-04-03 10:06:36', 'Question': 'I want to know Which customers do we work with for ship to Paris in last 3 months?', 'Answer': "select distinct BillingClientName from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCountry = 'Paris'"}
{'DateTime': '2024-04-03 10:08:21', 'Question': 'I want to know Which customers do we work with in last 3 months?', 'Answer': "select distinct BillingClientName from RevandVolume_ShipmentDate\n                WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                and OriginCountry = 'France'"}
{'DateTime': '2024-04-03 10:09:06', 'Question': 'I want to know Which customers do we work with in last 3 months for all countries?', 'Answer': 'select distinct BillingClientName from RevandVolume_ShipmentDate\n                WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()'}
{'DateTime': '2024-04-03 10:12:06', 'Question': 'I want to know Which customers do we work with in last 3 months for all countries?', 'Answer': 'select distinct BillingClientName from RevandVolume_ShipmentDate\n                WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()'}
{'DateTime': '2024-04-03 10:12:33', 'Question': 'I want to know Which customers do we work with in last 1 month for all countries?', 'Answer': 'select distinct BillingClientName from RevandVolume_ShipmentDate\n                WHERE ShipmentDate >= DATEADD(MONTH, -1, GETDATE())'}
{'DateTime': '2024-04-03 10:13:23', 'Question': 'I want to know the earned revenue from the shipments we exported to Paris in the last 3 months?', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCity = 'Paris'"}
{'DateTime': '2024-04-03 10:15:00', 'Question': 'I want to know the earned revenue from the shipments we exported to Dhaka in the last 3 months?', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCountry = 'BD'"}
{'DateTime': '2024-04-03 10:17:02', 'Question': 'I want to know the earned revenue from the shipments we exported to Dhaka in the last 3 months?', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCountry = 'BD'"}
{'DateTime': '2024-04-03 10:17:46', 'Question': 'I want to know the earned revenue from the shipments we exported to city Dhaka in the last 3 months?', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCity = 'Dhaka'"}
{'DateTime': '2024-04-03 10:18:00', 'Question': 'I want to know the earned revenue from the shipments we exported to city Dhaka in the last 3 months', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCity = 'Dhaka'"}
{'DateTime': '2024-04-03 10:23:28', 'Question': 'I want to know the earned revenue from the shipments we imported from city Dhaka in the last 3 months', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCountry = 'BD'\n                    and OriginCity = 'Dhaka'"}
{'DateTime': '2024-04-03 10:24:24', 'Question': 'I want to know the earned revenue from the shipments we imported from country bangladesh and city Dhaka in the last 3 months', 'Answer': "select SUM(Revenue_USD) AS Revenue from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCountry = 'Bangladesh' and OriginCity = 'Dhaka'"}
{'DateTime': '2024-04-03 10:25:55', 'Question': 'I want to know the Air freight tonnage of the shipment to Paris from other destination in last 3 months', 'Answer': "select SUM(ChargebleWeight) as Chargeble_Weight from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity = 'Paris'"}
{'DateTime': '2024-04-03 10:26:36', 'Question': 'I want to know the Air freight tonnage of the shipment to Colombo from other destination in last 3 months', 'Answer': "select SUM(Revenue_USD) / SUM(ChargebleWeight) from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity <> 'Colombo' and DestCity = 'Colombo'\n                    and TransportMode = 'AIR'"}
{'DateTime': '2024-04-03 10:29:16', 'Question': 'I want to know the Air freight rate given to customers from Colombo to Paris in last 3 months', 'Answer': "select SUM(Revenue_USD) / SUM(ChargebleWeight) as Chargeble_Weight from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and OriginCity = 'Colombo' and DestCity = 'Paris'\n                    and TransportMode = 'AIR'"}
{'DateTime': '2024-04-03 10:36:06', 'Question': 'I want to know the give me the average rate for Ex-works shipment which is shipped to London from Delhi', 'Answer': "select SUM(Revenue_USD) / SUM(ChargebleWeight) as Chargeble_Weight from RevandVolume_ShipmentDate\n                WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                and DestCity = 'Paris' and OriginCity = 'Colombo' \n                and MainDepCode = 'FEA' and INCO = 'FOB'"}
{'DateTime': '2024-04-03 10:37:19', 'Question': 'I want to know the incoterm wise airfreight rate for the shipmets that we have shiiped to Paris from Colombo', 'Answer': "select INCO, INCOTermDesc,SUM(Revenue_USD) / SUM(ChargebleWeight) as Chargeble_Weight from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCity = 'Paris' and OriginCity = 'Colombo' \n                    and MainDepCode = 'FEA'\n                    group by INCO, INCOTermDesc"}
{'DateTime': '2024-04-03 17:59:32', 'Question': 'what is the average airfreight rate for shipments shipped from colombo to new york in last 7 months?', 'Answer': "select SUM(Revenue_USD) / SUM(ChargebleWeight) as Chargeble_Weight from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= DATEADD(MONTH, -7, GETDATE()) AND ShipmentDate <= GETDATE()\n                    and DestCity = 'New York' and OriginCity = 'Colombo' \n                    and MainDepCode = 'FEA'\n                    and Packing_Mode = 'FCL'"}
{'DateTime': '2024-04-03 18:06:19', 'Question': 'give me the agent list who worked with us in Itally.', 'Answer': "select distinct AgentName from RevandVolume_ShipmentDate\n                    WHERE AgentCountryName like 'United kingdom' and INCO = 'EXW'\n                    and ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()"}
{'DateTime': '2024-04-03 18:07:39', 'Question': 'give me the agent list and their shipment count who worked with us in Italy.', 'Answer': "select distinct AgentName, count(*) as shipment_count from RevandVolume_ShipmentDate\n                    WHERE AgentCountryName like 'United kingdom' and INCO = 'EXW'\n                    and ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\n                    group by AgentName"}
{'DateTime': '2024-04-05 12:48:49', 'Question': 'i want to know the agent list and their shipment count who worked with us in India in last 2 months.', 'Answer': "select distinct AgentName, count(*) as ShipmentCount from RevandVolume_ShipmentDate\n                    WHERE AgentCountryName like 'United kingdom' and INCO = 'EXW'\n                    and ShipmentDate >= DATEADD(MONTH, -2, GETDATE()) AND ShipmentDate <= GETDATE()\n                    group by AgentName"}
{'DateTime': '2024-04-05 12:49:45', 'Question': 'i want to know the agent list and their shipment count who worked with us in Sri Lanka in last 2 months.', 'Answer': "select distinct AgentName, count(*) as shipment_count\n                    from RevandVolume_ShipmentDate\n                    WHERE AgentCountryName like 'United kingdom' and INCO = 'EXW'\n                    and ShipmentDate >= DATEADD(MONTH, -2, GETDATE()) AND ShipmentDate <= GETDATE()\n                    group by AgentName"}
{'DateTime': '2024-04-05 12:51:58', 'Question': 'who are the agents worked in Chicago?', 'Answer': "select distinct AgentName , AgentCity from RevandVolume_ShipmentDate\n                    WHERE AgentCity like 'Chicago%'"}
{'DateTime': '2024-04-05 12:53:21', 'Question': 'how many shipments we shipped from colombo to Istanbul in 2023?', 'Answer': "Select count(*) from RevandVolume_ShipmentDate\n                    where ShipmentDate >= DATEADD(MONTH, -3, GETDATE()) AND ShipmentDate <= GETDATE() \n                    and DestCity = 'Istanbul'\n                    and DestCountry = 'Turkey'\n                    and MainDepCode = 'FES'\n                    Group by OriginCity order by SUM(TEUSum) DESC"}
{'DateTime': '2024-04-05 12:54:56', 'Question': 'who are the clients we worked in Germeny in last 6 months?', 'Answer': "select distinct ClientName from RevandVolume_ShipmentDate\n                    WHERE AgentCountryName like 'United kingdom' and INCO = 'EXW'\n                    and ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()"}
{'DateTime': '2024-04-05 14:13:48', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months?', 'Answer': "select distinct BillingClientName from RevandVolume_ShipmentDate\n                WHERE ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\n                and OriginCountry = 'France'"}
{'DateTime': '2024-04-05 14:14:41', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments?', 'Answer': "select BillingClientName, count(ShipmentNumber) as ShipmentCount\n                from RevandVolume_ShipmentDate\n                where ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\n                and OriginCountry = 'France'\n                group by BillingClientName\n                order by ShipmentCount desc"}
{'DateTime': '2024-04-08 10:45:55', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments?', 'Answer': "select ClientName, count(ShipmentNumber) as NumberofShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and ClientName is not null\ngroup by ClientName \norder by NumberofShipments Desc"}
{'DateTime': '2024-04-08 12:34:19', 'Question': 'i need line chart who are the clients we worked in Germeny in last 6 months with no of shipments?', 'Answer': "select ClientName, count(ShipmentNumber) as NumberofShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and ClientName is not null\ngroup by ClientName \norder by NumberofShipments Desc"}
{'DateTime': '2024-04-08 13:03:53', 'Question': 'i need line chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as NumberOfShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and ClientName is not null\ngroup by ClientName \norder by NumberOfShipments Desc"}
{'DateTime': '2024-04-08 13:04:20', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as TotalShipment from RevandVolume_ShipmentDate\n                    WHERE ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\n                    and DestCity = 'Hamburg' and OriginCity = 'Colombo' \n                    and MainDepCode = 'FES' and ClientName is not null\n                    group by ClientName \n                    order by TotalShipment Desc"}
{'DateTime': '2024-04-08 13:11:13', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as NumberOfShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and ClientName is not null\ngroup by ClientName \norder by NumberOfShipments Desc"}
{'DateTime': '2024-04-08 13:14:21', 'Question': 'how much revenue we have done with agent flexport in 2023?', 'Answer': "select sum(Revenue_USD) from RevandVolume_ShipmentDate\nwhere AgentName = 'FLEXPORT INTERNATIONAL B.V.'\nand ShipmentDate >= '2023-01-01' and ShipmentDate <= '2023-12-31'"}
{'DateTime': '2024-04-08 13:16:08', 'Question': 'who are the agents we worked in Norway?', 'Answer': "select distinct AgentName from RevandVolume_ShipmentDate\n                    WHERE AgentCountryName like 'United kingdom' and INCO = 'EXW'\n                    and ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()"}
{'DateTime': '2024-04-08 17:32:28', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as NumberofShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and ClientName is not null\ngroup by ClientName \norder by NumberofShipments Desc"}
{'DateTime': '2024-04-08 17:38:31', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as Number_of_Shipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand OriginCountry = 'France'\ngroup by BillingClientName"}
{'DateTime': '2024-04-08 17:40:58', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as NumberOfShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand OriginCountry = 'France'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 17:25:32', 'Question': 'i need bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as NumberOfShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and Packing_Mode = 'FCL' and ClientName is not null\ngroup by ClientName"}
{'DateTime': '2024-04-18 17:31:03', 'Question': 'i need line chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as NumberofShipments\nfrom RevandVolume_ShipmentDate\nwhere DestCity = 'Hamburg' and ShipmentDate >= '2023-12-31' and ShipmentDate <= GETDATE()\ngroup by ClientName\norder by NumberofShipments desc"}
{'DateTime': '2024-04-18 17:31:50', 'Question': 'i need a table who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as NumberOfShipments\n                from RevandVolume_ShipmentDate\n                where ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\n                and DestCountry = 'DE'\n                group by BillingClientName\n                having count(ShipmentNumber) > 0;"}
{'DateTime': '2024-04-18 17:47:29', 'Question': 'i need a table who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(*) as No_of_shipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand DestCountry = 'DE'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 17:48:47', 'Question': 'i need a bar chart of who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select ClientName, count(ShipmentNumber) as NumberofShipments\nfrom RevandVolume_ShipmentDate\nwhere DestCity = 'Hamburg' and ShipmentDate >= '2023-12-31' and ShipmentDate <= GETDATE()\ngroup by ClientName\norder by NumberofShipments desc"}
{'DateTime': '2024-04-18 17:50:14', 'Question': 'i need a table of who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName,count(ShipmentNumber) as Number_of_Shipments from RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand OriginCountry = 'FR'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 17:51:49', 'Question': 'i need a table of who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(*) as shipment_count\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand DestCountry = 'Germany'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 17:55:20', 'Question': 'i need a bar chart of who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "```sql\nselect ClientName, count(ShipmentNumber) as NumberOfShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= '2023-12-31' AND ShipmentDate <= GETDATE()\nand DestCity = 'Hamburg' and OriginCity = 'Colombo' \nand MainDepCode = 'FES' and ClientName is not null\ngroup by ClientName \norder by NumberOfShipments Desc\n```"}
{'DateTime': '2024-04-18 17:55:59', 'Question': 'i need a bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as No_of_Shipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand DestCountry = 'DE'\ngroup by BillingClientName\norder by No_of_Shipments desc"}
{'DateTime': '2024-04-18 18:06:37', 'Question': 'i need a bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "```sql\nSELECT\n  BillingClientName,\n  COUNT(ShipmentNumber) AS Number_of_Shipments\nFROM RevandVolume_ShipmentDate\nWHERE\n  ShipmentDate >= DATEADD(MONTH, -6, GETDATE())\n  AND ShipmentDate <= GETDATE()\n  AND OriginCountry = 'FR'\nGROUP BY\n  BillingClientName\nORDER BY\n  Number_of_Shipments DESC;\n```"}
{'DateTime': '2024-04-18 18:06:58', 'Question': 'i need a bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(*) as count_shipments\n                from RevandVolume_ShipmentDate\n                where ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\n                and OriginCountry = 'France'\n                group by BillingClientName\n                order by count_shipments desc"}
{'DateTime': '2024-04-18 18:17:21', 'Question': 'i need a line chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as Number_of_Shipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand OriginCountry = 'FR'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 18:19:08', 'Question': 'i need a line chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as shipment_count\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand DestCountry = 'DE'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 18:19:34', 'Question': 'i need a bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as Number_of_Shipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand DestCountry = 'DE'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 18:20:11', 'Question': 'i need a bar chart who are the clients we worked in Germeny in last 6 months with no of shipments', 'Answer': "select BillingClientName, count(ShipmentNumber) as NumberOfShipments\nfrom RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -6, GETDATE()) AND ShipmentDate <= GETDATE()\nand DestCountry = 'DE'\ngroup by BillingClientName"}
{'DateTime': '2024-04-18 18:22:16', 'Question': 'I want to know the company wise revenue in last 3 months. create bar chart using it.', 'Answer': '```sql\nSELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 3, 31)\n                    GROUP BY Company\n```'}
{'DateTime': '2024-04-18 18:24:36', 'Question': 'I want to know the company wise revenue in last 3 months. create bar chart using it.', 'Answer': '```sql\nSELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 3, 31)\n                    GROUP BY Company\n                    ORDER BY Revenue DESC\n```'}
{'DateTime': '2024-04-18 18:41:19', 'Question': 'i want to know the profit in last 4 months by the each company.', 'Answer': 'select `Company`, sum(`Profit_USD`) as TotalProfit from RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -4, GETDATE()) AND ShipmentDate <= GETDATE()\ngroup by `Company`'}
{'DateTime': '2024-04-18 18:42:00', 'Question': 'i want to know the profit in last 4 months by the each company.', 'Answer': 'select sum(Profit_USD) AS GrossProfit, companyname from RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -4, GETDATE()) AND ShipmentDate <= GETDATE()\ngroup by companyname'}
{'DateTime': '2024-04-18 18:43:45', 'Question': 'i want to know the profit in last 4 months by the each company using bar chart.', 'Answer': '```sql\nSELECT \n    Company,\n    SUM(Profit_LocalCur) AS Revenue\nFROM\n    AcctShipmentFact_ViewClient\nWHERE\n    RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()), 1, 1)\nGROUP BY\n    Company\nORDER BY\n    Revenue DESC\n```'}
{'DateTime': '2024-04-18 18:44:07', 'Question': 'i want to know the profit in last 4 months by the each company using bar chart.', 'Answer': '```sql\nSELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()), 1, 1)\n                    GROUP BY Company\n                    ORDER BY Revenue DESC\n```'}
{'DateTime': '2024-04-18 18:44:33', 'Question': 'i want to know the profit in last 4 months by the each company.', 'Answer': 'select `Company`, sum(`Profit_USD`) as GrossProfit from RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -4, GETDATE()) AND ShipmentDate <= GETDATE()\ngroup by `Company`'}
{'DateTime': '2024-04-18 18:44:55', 'Question': 'i want to know the profit in last 4 months by the each company.', 'Answer': 'select `Company`, sum(`Profit_USD`) as `Total Profit` from RevandVolume_ShipmentDate\nwhere ShipmentDate >= DATEADD(MONTH, -4, GETDATE()) AND ShipmentDate <= GETDATE()\ngroup by `Company`'}
{'DateTime': '2024-04-18 18:45:29', 'Question': 'i want to know the profit in last 4 months by the each company.', 'Answer': 'select `Company`, sum(`Profit_USD`) as GrossProfit from RevandVolume_ShipmentDate\n                    where ShipmentDate >= DATEADD(MONTH, -4, GETDATE()) AND ShipmentDate <= GETDATE()\n                    group by `Company`'}
{'DateTime': '2024-04-18 18:45:52', 'Question': 'i want to know the profit in last 5 months by the each company.', 'Answer': 'SELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 5, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31)\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 15:49:14', 'Question': 'I want to see the last yar revenue by each company.', 'Answer': 'SELECT Company,SUM(RevenueLocalcur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31)\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 15:55:13', 'Question': 'I want to see the last month revenue by each company.', 'Answer': '```sql\nSELECT\n  c.CompanyName,\n  SUM(r.Revenue_USD) AS Revenue_USD\nFROM RevandVolume_ShipmentDate AS r\nJOIN AcctShipmentFact_ViewClient AS c\n  ON r.Company = c.Company\nWHERE\n  r.ShipmentDate >= DATEADD(MONTH, -1, GETDATE())\nGROUP BY\n  c.CompanyName;\n```'}
{'DateTime': '2024-04-19 15:55:43', 'Question': 'I want to see the last month revenue by each company.', 'Answer': '```sql\nSELECT\n  c.CompanyName,\n  SUM(r.Revenue_USD) AS Revenue_USD\nFROM RevandVolume_ShipmentDate AS r\nJOIN AcctShipmentFact_ViewClient AS c\n  ON r.Company = c.Company\nWHERE\n  r.ShipmentDate >= DATEADD(MONTH, -1, GETDATE())\n  AND r.ShipmentDate <= GETDATE()\nGROUP BY\n  c.CompanyName\nORDER BY\n  Revenue_USD DESC;\n```'}
{'DateTime': '2024-04-19 15:56:26', 'Question': 'I want to see the last year revenue by each company.', 'Answer': 'SELECT Company,SUM(RevenueLocalcur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31)\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 15:59:38', 'Question': 'I want to see the Revenue by each Year', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:01:29', 'Question': 'I want to see the Revenue by each Year in a table.', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:08:19', 'Question': 'I want to see the Revenue by each Year in a table.', 'Answer': "```sql\nSELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)\n```"}
{'DateTime': '2024-04-19 16:08:44', 'Question': 'I want to see the Revenue by each Year in a table.', 'Answer': "```sql\nSELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)\n```"}
{'DateTime': '2024-04-19 16:09:15', 'Question': 'I want to see the Revenue by each Year.', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:10:21', 'Question': 'I want to see the Revenue by each Year in a line chart.', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)\n                    ORDER BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:13:21', 'Question': 'I want to see the Revenue by each Year in a table.', 'Answer': "```sql\nSELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)\n```"}
{'DateTime': '2024-04-19 16:13:44', 'Question': 'I want to see the Revenue by each Year in a table.', 'Answer': "```sql\nSELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)\n```"}
{'DateTime': '2024-04-19 16:14:14', 'Question': 'I want to see the Revenue by each Year in a table format.', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:15:29', 'Question': 'I want to see the Revenue by each Company in a table format.', 'Answer': 'SELECT Company,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 16:16:30', 'Question': 'I want to see the Revenue by each Company in a bar chart.', 'Answer': 'SELECT CompanyName, SUM(Revenue_USD) AS TotalRevenueUSD \n                    FROM RevandVolume_ShipmentDate \n                    GROUP BY CompanyName'}
{'DateTime': '2024-04-19 16:18:09', 'Question': 'I want to see the Revenue by each Company in a bar chart use Company code as a Company Name.', 'Answer': 'SELECT CompanyCode, SUM(Revenue_USD) AS TotalRevenueUSD \nFROM RevandVolume_ShipmentDate\nGROUP BY CompanyCode\nORDER BY TotalRevenueUSD DESC;'}
{'DateTime': '2024-04-19 16:18:51', 'Question': 'I want to see the Revenue by each Company in a bar chart use Company code as a Company Name.', 'Answer': 'SELECT CompanyCode, SUM(Revenue_USD) AS TotalRevenueUSD \nFROM RevandVolume_ShipmentDate\nGROUP BY CompanyCode\nORDER BY TotalRevenueUSD DESC;'}
{'DateTime': '2024-04-19 16:19:24', 'Question': 'I want to see the Revenue by each Company in a bar chart use Company code.', 'Answer': 'SELECT CompanyCode, SUM(Revenue_USD) AS TotalRevenueUSD \n                    FROM RevandVolume_ShipmentDate \n                    GROUP BY CompanyCode'}
{'DateTime': '2024-04-19 16:20:10', 'Question': 'I want to see the Revenue by each Company in a bar chart.', 'Answer': 'SELECT CompanyName, SUM(Revenue_USD) AS TotalRevenueUSD \n                    FROM RevandVolume_ShipmentDate \n                    GROUP BY CompanyName'}
{'DateTime': '2024-04-19 16:20:48', 'Question': 'I want to see the Revenue by each Company in a scatter plot.', 'Answer': 'SELECT CompanyName, SUM(Revenue_USD) AS TotalRevenueUSD \n                    FROM RevandVolume_ShipmentDate \n                    GROUP BY CompanyName'}
{'DateTime': '2024-04-19 16:24:13', 'Question': 'I want to see the Profit in India by each year in a table.', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(Profit_LocalCur) AS Profit\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:25:31', 'Question': 'I want to see the Profit in India by each year in a bar graph.', 'Answer': "```sql\nSELECT\n    SUBSTRING(RevandVolume_ShipmentDate.`ShipmentDate`, 1, 4) AS `Year`,\n    SUM(RevandVolume_ShipmentDate.`Profit_USD`) AS `Total Profit`\nFROM\n    RevandVolume_ShipmentDate\nWHERE\n    RevandVolume_ShipmentDate.`DestCountry` = 'India'\nGROUP BY\n    `Year`\nORDER BY\n    `Year`;\n```"}
{'DateTime': '2024-04-19 16:25:56', 'Question': 'I want to see the Profit in India by each year in a bar graph.', 'Answer': "```sql\nSELECT \n    SUBSTRING(RevRecDate,1,4) AS 'Year',\n    SUM(Profit_USD) AS 'Total Profit'\nFROM \n    AcctShipmentFact_ViewClient\nWHERE \n    DestCountry = 'India'\nGROUP BY \n    SUBSTRING(RevRecDate,1,4)\nORDER BY \n    SUBSTRING(RevRecDate,1,4)\n```"}
{'DateTime': '2024-04-19 16:28:36', 'Question': 'I want to see the Revenue by each year In company IND', 'Answer': "SELECT YEAR(RevRecDate) AS Year,SUM(RevenueLocalcur) AS Revenue\n                    FROM AcctShipmentFact_ViewClient\n                    WHERE Company = 'IND'\n                    GROUP BY YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:30:29', 'Question': 'I want to see the Revenue comparison in year 2022 and 2023 In company IND', 'Answer': "SELECT \n    YEAR(RevRecDate) AS Year,\n    SUM(RevenueLocalcur) AS Revenue\nFROM \n    AcctShipmentFact_ViewClient\nWHERE \n    Company = 'IND'\n    AND YEAR(RevRecDate) IN (2022, 2023)\nGROUP BY \n    YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:32:15', 'Question': 'I want to see the Profit comparison in year 2022 and 2023 In company CMB', 'Answer': 'The question is unanswerable from the given source.'}
{'DateTime': '2024-04-19 16:32:48', 'Question': 'I want to see the Profit comparison in year 2022 and 2023 In company CMB', 'Answer': 'The provided tables do not contain data for the year 2022 and 2023, so I cannot extract the requested data from the provided context.'}
{'DateTime': '2024-04-19 16:33:28', 'Question': 'I want to see the Profit comparison in year 2022 and 2023 In company DAC', 'Answer': "```sql\nSELECT \n    YEAR(RevRecDate) AS 'Year',\n    SUM(Profit_USD) AS 'Total Profit'\nFROM AcctShipmentFact_ViewClient\nWHERE \n    YEAR(RevRecDate) IN (2022, 2023) AND Company = 'DAC'\nGROUP BY \n    YEAR(RevRecDate)\n```"}
{'DateTime': '2024-04-19 16:33:58', 'Question': 'I want to see the Profit comparison in year 2022 and 2023 In company DAC', 'Answer': "SELECT \n    YEAR(RevRecDate) AS 'Year',\n    SUM(Profit_LocalCur) AS 'Total Profit'\nFROM \n    AcctShipmentFact_ViewClient\nWHERE \n    Company = 'DAC'\n    AND YEAR(RevRecDate) IN (2022, 2023)\nGROUP BY \n    YEAR(RevRecDate)\nORDER BY \n    YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 16:35:19', 'Question': 'I want to see the Revenue growth in year 2022 and 2023 In company IND', 'Answer': "SELECT \n    YEAR(RevRecDate) AS Year,\n    SUM(Profit_LocalCur) AS Revenue\nFROM \n    AcctShipmentFact_ViewClient\nWHERE \n    Company = 'IND'\n    AND YEAR(RevRecDate) IN (2022, 2023)\nGROUP BY \n    YEAR(RevRecDate)\nORDER BY \n    YEAR(RevRecDate)"}
{'DateTime': '2024-04-19 17:18:30', 'Question': 'I need to see yearly No of jobs count.', 'Answer': 'SELECT\n    YEAR(JobOpenDate) AS JobYear,\n    COUNT(*) AS JobCount\nFROM\n    JobCountByJobOpenDate\nGROUP BY\n    JobYear\nORDER BY\n    JobYear;'}
{'DateTime': '2024-04-19 17:36:49', 'Question': 'I need to see yearly No of jobs count in bar chart.', 'Answer': "SELECT\n    COUNT(DISTINCT JobNum) AS Number_of_Jobs,\n    STRFTIME('%Y', JobOpenDate) AS Year\nFROM\n    JobCountByJobOpenDate\nGROUP BY\n    Year\nORDER BY\n    Year;"}
{'DateTime': '2024-04-19 17:38:21', 'Question': 'I want to know the company wise revenue in last 3 months. create bar chart using it.', 'Answer': 'SELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()), 12, 31)\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 17:39:54', 'Question': 'I want to know the company wise revenue in last 3 months. create line chart using it.', 'Answer': 'SELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31)\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 17:41:42', 'Question': 'I want to know the company wise revenue in last year.', 'Answer': 'SELECT Company,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31)\n                    GROUP BY Company'}
{'DateTime': '2024-04-19 17:42:52', 'Question': 'I want to top 10 consignors by revenue in last year.', 'Answer': 'SELECT TOP 10 ConsignorName,SUM(Profit_LocalCur) AS Revenue \n                    FROM AcctShipmentFact_ViewClient AS asf\n                    WHERE RevRecDate BETWEEN DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) and DATEFROMPARTS(YEAR(GETDATE()) - 1, 12, 31)\n                    GROUP BY ConsignorName\n                    ORDER BY SUM(Profit_LocalCur) DESC'}
{'DateTime': '2024-04-19 17:44:46', 'Question': 'Can you show total sales and outstanding amounts for all shipments to Europe in the last 9 months?', 'Answer': "SELECT s.BillingClientName AS ClientName, SUM(s.Revenue_USD) AS TotalSalesUSD, SUM(r.OutStanding_USD) AS OutstandingUSD FROM RevandVolume_ShipmentDate s INNER JOIN ReceivableWithCreditLimit r ON r.Oh_code = s.BillingClientCode WHERE s.DestContinent = 'Europe'  AND s.ShipmentDate >= DATEADD(MONTH, -9, GETDATE()) GROUP BY s.BillingClientName"}
